"""create weather_cache table

Revision ID: 36049b77ae01
Revises: 
Create Date: 2025-04-19 15:37:52.233590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36049b77ae01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_cache_location'), ['location'], unique=False)
        batch_op.create_index('ix_weather_cache_location_updated_at', ['location', 'updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_weather_cache_location_updated_at')
        batch_op.drop_index(batch_op.f('ix_weather_cache_location'))

    op.drop_table('weather_cache')
    # ### end Alembic commands ###
